settings:
  prefix: "&8[&bCrazyAuctions&8]: " # The prefix used in front of messages.

  verbose-logging: false # Whether you want to have extra logging enabled... Currently does nothing!

  update-checker: true # Whether you want to be notified when an update is published to Modrinth.
  toggle-metrics: true # Whether you want your server statistics to be sent to https://bstats.org/ ( Requires a restart! )
  config-version: 1.0 # DO NOT TOUCH THIS: We use this to identify if configs are outdated.

  data-storage:
    # How the plugin should store data
    #
    # - Your Options
    # | Remote Database Types - You need to supply connection information.
    # |» MySQL *NOT IMPLEMENTED*
    # |» MariaDB ( Recommended over MySQL ) *NOT IMPLEMENTED*
    #
    # | Local Database Types
    # |» H2 *NOT IMPLEMENTED*
    #
    # | Text File Based Storage
    # |» JSON (.json files) *DEFAULT
    storage-method: JSON