Settings:
  Prefix: '&7[&4Crazy &bAuctions&7]: '
  Timers:
    Selling-Time: 2d
    Bidding-Time: 2h
    Expire-Time: 10d
    Bidding-Winner-Time: 20d
  Multi-World:
    Enabled: true
    Per-World: true #If set to false it will use world groups.
    World-Groups: #Groups of worlds that have their CA's connected. If none are found it will auto set to Per-World.
      1: #Group ID
        - 'Survival_1' #List of worlds in the group.
        - 'Survival_2'
      2:
        - 'OP_Prison_1'
        - 'OP_Prison_2'
      3:
        - 'Sky_Block_1'
        - 'Sky_Block_2'
  Menu-Pages:
    Category-Menu:
      Name: '&l&7>> &8Auction Categories'
    Auction-Selling:
      Name: '&l&7>> &8Selling Auction House'
    Auction-Bidding:
      Name: '&l&7>> &8Bidding Auction House'
    Current-Sales:
      Name: '&l&7>> &8Currently For Sale'
    Expired:
      Name: '&l&7>> &8Expired Items'
    Buying-Page:
      Name: '&l&7>> &8Confirm Your Purchase'
    Bidding-Page:
      Name: '&l&7>> &8Place Your Bid'
  Buttons:
    Current-Items:
      Enabled: true
      Slot: 46
      Item: 'DIAMOND'
      Name: '&6Items You are Selling'
      Lore:
        - '&aClick here to view all the items you'
        - '&aare currently selling on the auction.'
    Expired-Items:
      Enabled: true
      Slot: 47
      Item: 'POISONOUS_POTATO'
      Name: '&6Collect Expired / Canceled Items'
      Lore:
        - '&aClick here to view and collect all of the'
        - '&aitems you have canceled or has expired.'
    Next-Page:
      Enabled: true
      Slot: 51
      Item: 'PAPER'
      Name: '&6Next Page'
      Lore: {}
    Refresh:
      Enabled: true
      Slot: 50
      Item: 'SUNFLOWER'
      Name: '&6Refresh Page'
      Lore: {}
    Previous-Page:
      Enabled: true
      Slot: 49
      Item: 'PAPER'
      Name: '&6Previous Page'
      Lore: {}
    Category-1:
      Enabled: true
      Slot: 48
      Item: 'CHEST'
      Name: '&6Categories'
      Lore:
        - '&bCurrent Category: &6%category%'
        - '&aWant to see items in specific categories?'
        - '&aClick here to see all categories of items.'
    Category-2:
      Enabled: true
      Slot: 52
      Item: 'CHEST'
      Name: '&6Categories'
      Lore:
        - '&bCurrent Category: &6%category%'
        - '&aWant to see items in specific categories?'
        - '&aClick here to see all categories of items.'
    Back-Button:
      Enabled: true
      Slot: 46
      Item: 'PAPER'
      Name: '&6Back'
      Lore: {}
    Return-All-Button:
      Enabled: true
      Slot: 50
      Item: 'FLOWER_POT'
      Name: '&6Return All'
      Lore:
        - '&aClick here to return all cancelled'
        - '&aand expired items to your inventory.'
    Confirm:
      Enabled: true
      Item: 'LIME_STAINED_GLASS_PANE'
      Name: '&aConfirm'
      Lore: {}
    Cancel:
      Enabled: true
      Item: 'RED_STAINED_GLASS_PANE'
      Name: '&cCancel'
      Lore: {}
    Your-Item:
      Enabled: true
      Item: 'BARRIER'
      Name: '&cYou can''t purchase your own item!'
      Lore: {}
    Cant-Afford:
      Enabled: true
      Item: 'BARRIER'
      Name: '&cYou can''t afford this item!'
      Lore: {}
    Top-Bidder:
      Enabled: true
      Item: 'BARRIER'
      Name: '&cYou are already the top bidder.'
      Lore: {}
    Bidding-Explain:
      Enabled: true
      Item: 'BLACK_STAINED_GLASS_PANE'
      Name: '&7How bidding works'
      Lore:
        - '&7<--&aAdd &cRemove&7-->'
        - '&9Your Current Bid: &e$%Bid%'
        - '&9Current Top Bid: &e$%topbid%'
    Bid-Confirm:
      Enabled: true
      Item: 'LIGHT_BLUE_STAINED_GLASS_PANE'
      Name: '&bConfirm Bid'
      Lore:
        - '&7Click here to confirm your bid.'
    What-Is-This:
      Selling:
        Enabled: true
        Slot: 54
        Item: 'BOOK'
        Name: '&6What Is This Page?'
        Lore:
          - '&aThis is the crazy auctions, here you can'
          - '&aput items for sale, and buy items'
          - '&athat others have put for sale.'
          - ''
          - '&aThe auction is also a great place to make'
          - '&amoney by selling items that others'
          - '&amay be interested in buying.'
      Bidding:
        Enabled: true
        Slot: 54
        Item: 'BOOK'
        Name: '&6What Is This Page?'
        Lore:
          - '&aThis is the crazy auctions, here you can'
          - '&aput items for sale, and bid on items'
          - '&athat others have put for sale.'
          - ''
          - '&aThe bidding auction is also a great place to'
          - '&amake money by bidding off items that others'
          - '&amay be interested in bidding on.'
      Current-Items:
        Enabled: true
        Slot: 54
        Item: 'BOOK'
        Name: '&6What Is This Page?'
        Lore:
          - '&aThese are your current listings, all of'
          - '&athe items you currently have listed on'
          - '&acrazy auctions are displayed here.'
          - ''
          - '&aYou can cancel and view your listings'
          - '&aexpire time here.'
      Expired-Items:
        Enabled: true
        Slot: 54
        Item: 'BOOK'
        Name: '&6What Is This Page?'
        Lore:
          - '&aThis page houses all of your cancelled and'
          - '&aexpired items, when a listings is cancelled'
          - '&aor expires you will be able to return that'
          - '&aitem back to you from this menu.'
          - ''
          - '&aJust click on the item and if you have enough'
          - '&ainventory space you will receive that item.'
      Viewing:
        Enabled: true
        Slot: 50
        Item: 'BOOK'
        Name: '&6What Is This Page?'
        Lore:
          - '&aThis page shows all the items that'
          - '&aa player has currently on the bidding'
          - '&aand selling market. You can quickly see'
          - '&awhat a specific player is selling.'
      Categories:
        Enabled: true
        Slot: 54
        Item: 'BOOK'
        Name: '&6What Is This Page?'
        Lore:
          - '&aThis page shows all the categories'
          - '&athat you can choose from. When you click'
          - '&aa category it will open the gui with only'
          - '&aitems that belong to that category.'
  Categories:
    Armor:
      Display:
        Slot: 11
        Item: 'GOLDEN_CHESTPLATE'
        Name: '&6&lArmor'
        Lore:
          - '&7This category contains all'
          - '&7armor that is currently being sold.'
      Items:
        - 'LEATHER_HELMET'
        - 'CHAINMAIL_HELMET'
        - 'GOLDEN_HELMET'
        - 'IRON_HELMET'
        - 'DIAMOND_HELMET'
        - 'LEATHER_CHESTPLATE'
        - 'CHAINMAIL_CHESTPLATE'
        - 'GOLDEN_CHESTPLATE'
        - 'IRON_CHESTPLATE'
        - 'DIAMOND_CHESTPLATE'
        - 'LEATHER_LEGGINGS'
        - 'CHAINMAIL_LEGGINGS'
        - 'GOLDEN_LEGGINGS'
        - 'IRON_LEGGINGS'
        - 'DIAMOND_LEGGINGS'
        - 'LEATHER_BOOTS'
        - 'CHAINMAIL_BOOTS'
        - 'GOLDEN_BOOTS'
        - 'IRON_BOOTS'
        - 'DIAMOND_BOOTS'
    Weapons:
      Display:
        Slot: 12
        Item: 'GOLDEN_SWORD'
        Name: '&6&lWeapons'
        Lore:
          - '&7This category contains all'
          - '&7weapons that are currently being sold.'
      Items:
        - 'WOODEN_SWORD'
        - 'STONE_SWORD'
        - 'IRON_SWORD'
        - 'GOLDEN_SWORD'
        - 'DIAMOND_SWORD'
        - 'WOODEN_AXE'
        - 'STONE_AXE'
        - 'IRON_AXE'
        - 'GOLDEN_AXE'
        - 'DIAMOND_AXE'
        - 'BOW'
    Tools:
      Display:
        Slot: 13
        Item: 'GOLDEN_PICKAXE'
        Name: '&6&lTools'
        Lore:
          - '&7This category contains all'
          - '&7tools that are currently being sold.'
      Items:
        - 'WOODEN_PICKAXE'
        - 'STONE_PICKAXE'
        - 'IRON_PICKAXE'
        - 'GOLDEN_PICKAXE'
        - 'DIAMOND_PICKAXE'
        - 'WOODEN_AXE'
        - 'STONE_AXE'
        - 'IRON_AXE'
        - 'GOLDEN_AXE'
        - 'DIAMOND_AXE'
        - 'WOODEN_SHOVEL'
        - 'STONE_SHOVEL'
        - 'IRON_SHOVEL'
        - 'GOLDEN_SHOVEL'
        - 'DIAMOND_SHOVEL'
        - 'WOODEN_HOE'
        - 'STONE_HOE'
        - 'IRON_HOE'
        - 'GOLDEN_HOE'
        - 'DIAMOND_HOE'
        - 'SHEARS'
    Food:
      Display:
        Slot: 14
        Item: 'GOLDEN_APPLE'
        Name: '&6&lFood'
        Lore:
          - '&7This category contains all'
          - '&7food that is currently being sold.'
      Items:
        - 'APPLE'
        - 'BAKED_POTATO'
        - 'BEEF'
        - 'BEETROOT'
        - 'BEETROOT_SOUP'
        - 'BREAD'
        - 'CARROT'
        - 'CHICKEN'
        - 'CHORUS_FRUIT'
        - 'COD'
        - 'COOKED_BEEF'
        - 'COOKED_CHICKEN'
        - 'COOKED_COD'
        - 'COOKED_MUTTON'
        - 'COOKED_PORKCHOP'
        - 'COOKED_RABBIT'
        - 'COOKED_SALMON'
        - 'COOKIE'
        - 'DRIED_KELP'
        - 'ENCHANTED_GOLDEN_APPLE'
        - 'GOLDEN_APPLE'
        - 'GOLDEN_CARROT'
        - 'HONEY_BOTTLE'
        - 'MELON_SLICE'
        - 'MUSHROOM_STEW'
        - 'MUTTON'
        - 'POISONOUS_POTATO'
        - 'PORKCHOP'
        - 'POTATO'
        - 'PUFFERFISH'
        - 'PUMPKIN_PIE'
        - 'RABBIT'
        - 'RABBIT_STEW'
        - 'ROTTEN_FLESH'
        - 'SALMON'
        - 'SPIDER_EYE'
        - 'SUSPICIOUS_STEW'
        - 'SWEET_BERRIES'
        - 'TROPICAL_FISH'
    Potions:
      Display:
        Slot: 15
        Item: 'POTION'
        Name: '&6&lPotions'
        Lore:
          - '&7This category contains all'
          - '&7potions that are currently being sold.'
      Items:
        - 'POTION'
        - 'SPLASH_POTION'
        - 'LINGERING_POTION'
    Blocks:
      Display:
        Slot: 16
        Item: 'GRASS_BLOCK'
        Name: '&6&lBlocks'
        Lore:
          - '&7This category contains all'
          - '&7blocks that are currently being sold.'
      Items:
        - ''
    Other:
      Display:
        Slot: 17
        Item: 'GOLD_NUGGET'
        Name: '&6&lOthers'
        Lore:
          - '&7This category contains all the'
          - '&7other items currently being sold.'
      Items:
        - ''