Settings:
  Categories:
    Armor:
      Display:
        Slot: 11
        Item: 'GOLD_CHESTPLATE'
        Name: '&6&lArmor'
        Lore:
          - '&7This category contains all'
          - '&7armor that is currently being sold.'
      Items:
        - 'LEATHER_HELMET'
        - 'CHAINMAIL_HELMET'
        - 'GOLD_HELMET'
        - 'IRON_HELMET'
        - 'DIAMOND_HELMET'
        - 'LEATHER_CHESTPLATE'
        - 'CHAINMAIL_CHESTPLATE'
        - 'GOLD_CHESTPLATE'
        - 'IRON_CHESTPLATE'
        - 'DIAMOND_CHESTPLATE'
        - 'LEATHER_LEGGINGS'
        - 'CHAINMAIL_LEGGINGS'
        - 'GOLD_LEGGINGS'
        - 'IRON_LEGGINGS'
        - 'DIAMOND_LEGGINGS'
        - 'LEATHER_BOOTS'
        - 'CHAINMAIL_BOOTS'
        - 'GOLD_BOOTS'
        - 'IRON_BOOTS'
        - 'DIAMOND_BOOTS'
    Weapons:
      Display:
        Slot: 12
        Item: 'GOLD_SWORD'
        Name: '&6&lWeapons'
        Lore:
          - '&7This category contains all'
          - '&7weapons that are currently being sold.'
      Items:
        - 'WOOD_SWORD'
        - 'STONE_SWORD'
        - 'IRON_SWORD'
        - 'GOLD_SWORD'
        - 'DIAMOND_SWORD'
        - 'WOOD_AXE'
        - 'STONE_AXE'
        - 'IRON_AXE'
        - 'GOLD_AXE'
        - 'DIAMOND_AXE'
        - 'BOW'
    Tools:
      Display:
        Slot: 13
        Item: 'GOLD_PICKAXE'
        Name: '&6&lTools'
        Lore:
          - '&7This category contains all'
          - '&7tools that are currently being sold.'
      Items:
        - 'WOOD_PICKAXE'
        - 'STONE_PICKAXE'
        - 'IRON_PICKAXE'
        - 'GOLD_PICKAXE'
        - 'DIAMOND_PICKAXE'
        - 'WOOD_AXE'
        - 'STONE_AXE'
        - 'IRON_AXE'
        - 'GOLD_AXE'
        - 'DIAMOND_AXE'
        - 'WOOD_SHOVEL'
        - 'STONE_SHOVEL'
        - 'IRON_SHOVEL'
        - 'GOLD_SHOVEL'
        - 'DIAMOND_SHOVEL'
        - 'WOOD_HOE'
        - 'STONE_HOE'
        - 'IRON_HOE'
        - 'GOLD_HOE'
        - 'DIAMOND_HOE'
        - 'SHEARS'
    Food:
      Display:
        Slot: 14
        Item: 'GOLDEN_APPLE'
        Name: '&6&lFood'
        Lore:
          - '&7This category contains all'
          - '&7food that is currently being sold.'
      Items:
        - 'APPLE'
        - 'MUSHROOM_SOUP'
        - 'BREAD'
        - 'PORK'
        - 'GRILLED_PORK'
        - 'GOLDEN_APPLE'
        - 'RAW_FISH'
        - 'COOKED_FISH'
        - 'COOKIE'
        - 'MELON'
        - 'RAW_BEEF'
        - 'COOKED_BEEF'
        - 'RAW_CHICKEN'
        - 'COOKED_CHICKEN'
        - 'ROTTEN_FLESH'
        - 'SPIDER_EYE'
        - 'CARROT_ITEM'
        - 'POTATO_ITEM'
        - 'BAKED_POTATO'
        - 'POISONOUS_POTATO'
        - 'GOLDEN_CARROT'
        - 'PUMPKIN_PIE'
        - 'RABBIT'
        - 'COOKED_RABBIT'
        - 'RABBIT_STEW'
        - 'MUTTON'
        - 'COOKED_MUTTON'
        - 'CHORUS_FRUIT'
        - 'BEETROOT'
        - 'BEETROOT_SOUP'
    Potions:
      Display:
        Slot: 15
        Item: 'POTION'
        Name: '&6&lPotions'
        Lore:
          - '&7This category contains all'
          - '&7potions that are currently being sold.'
      Items:
        - 'POTION'
    Blocks:
      Display:
        Slot: 16
        Item: 'GRASS'
        Name: '&6&lBlocks'
        Lore:
          - '&7This category contains all'
          - '&7blocks that are currently being sold.'
      Items:
        - ''
    Other:
      Display:
        Slot: 17
        Item: 'GOLD_NUGGET'
        Name: '&6&lOthers'
        Lore:
          - '&7This category contains all the'
          - '&7other items currently being sold.'
      Items:
        - ''