name: "CrazyCrates"
main: "${group}.CrazyAuctions"

authors: [BadBones69, RyderBelserion]

version: ${version}
api-version: "1.13"
description: ${description}

softdepend: [Vault]

website: https://modrinth.com/plugin/crazyauctions

commands:
  ca:
    description: Opens the Crazy Auctions GUI.
    aliases: [crazyauction, crazyauctions, ah, hdv]