name: "CrazyAuctions"
main: "${group}.CrazyAuctions"

authors: [BadBones69, RyderBelserion]

version: ${version}
api-version: "1.13"
description: ${description}

softdepend: [Vault]

website: https://modrinth.com/plugin/crazyauctions

commands:
  crazyauctions:
    description: Opens the main menu for CrazyAuctions.