[versions]

# Paper Team
paper = "1.19.2-R0.1-SNAPSHOT"

# Bukkit
bukkit-bstats = "3.0.0"

# Placeholders
placeholder-api = "2.11.2"

# Misc Libraries
vault-api = "1.7"

[libraries]

# Paper Team
paper = { module = "io.papermc.paper:paper-api", version.ref = "paper" }

# Bukkit
bukkit-bstats = { module = "org.bstats:bstats-bukkit", version.ref = "bukkit-bstats" }

# Misc Libraries
vault-api = { module = "com.github.MilkBowl:VaultAPI", version.ref = "vault-api" }