[versions]

# Minecraft
paper = "1.19.4-R0.1-SNAPSHOT"

# CrazyCore
crazycore = "618b89a"

# Adventure
adventure = "4.13.0"

ktor = "2.2.4"
kotlin = "1.8.20-RC"

[libraries]

# Minecraft
papermc = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
paperlib = { module = "io.papermc:paperlib", version = "1.0.8-SNAPSHOT" }
paperweight = { module = "io.papermc.paperweight:paperweight-userdev", version = "1.5.3" }

# Adventure
adventure_api = { module = "net.kyori:adventure-api", version.ref = "adventure" }
adventure_text = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure" }

# CrazyCore
crazycore_api = { module = "us.crazycrew.crazycore:crazycore-api", version.ref = "crazycore" }
crazycore_paper = { module = "us.crazycrew.crazycore:crazycore-paper", version.ref = "crazycore" }

# Triumph Team
triumph_cmds = { module = "dev.triumphteam:triumph-cmd-bukkit", version = "2.0.0-SNAPSHOT" }
triumph_gui = { module = "dev.triumphteam:triumph-gui", version = "3.1.2" }

# Config
yaml = { module = "me.carleslc.Simple-YAML:Simple-Yaml", version = "1.8.3" }
config_me = { module = "ch.jalu:configme", version = "1.3.0" }

# Misc
bstats_bukkit = { module = "org.bstats:bstats-bukkit", version = "3.0.0" }
vault_api = { module = "com.github.MilkBowl:VaultAPI", version = "1.7" }

# Holograms
holographic_displays = { module = "me.filoghost.holographicdisplays:holographicdisplays-api", version = "3.0.1" }
decent_holograms = { module = "com.github.decentsoftware-eu:decentholograms", version = "2.8.1" }

cmi_api = { module = "com.Zrips.CMI:CMI-API", version = "9.3.1.5" }
cmi_lib = { module = "net.zrips.CMILib:cmi-lib-api", version = "1.2.5.3" }

# Placeholders
placeholder_api = { module = "me.clip:placeholderapi", version = "2.11.2" }

# Kotlin
ktor-core = { module = "io.ktor:ktor-client-core-jvm", version.ref = "ktor" }
ktor-cio = { module = "io.ktor:ktor-client-cio-jvm", version.ref = "ktor" }
ktor-content = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-gson = { module = "io.ktor:ktor-serialization-gson", version.ref = "ktor" }

kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin"}
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.6.4" }

shadow = { module = "com.github.johnrengelman:shadow", version = "8.1.0" }

turtle = { module = "com.lordcodes.turtle:turtle", version = "0.8.0" }