name: "CrazyCrates"
main: "${group}.CrazyAuctions"

authors: [BadBones69, RyderBelserion]

version: ${version}
api-version: "1.13"
description: ${description}
website: ${website}

softdepend: [CMI, HolographicDisplays, DecentHolograms, PlaceholderAPI]

commands:
  crazyauctions:
    description: The base command for Crazy Auctions
    aliases: [ca, ah, crazyauction]