settings:
  # The language file to use from the locale folder.
  # Supported languages are English(en).
  language-file: "locale-en.yml"
  # Whether you want to have verbose logging enabled.
  verbose: true
  # Whether you want metrics to be enabled.
  metrics: true
  # Sends you update notifications for when an update is available!
  # You either need crazyauctions.command.admin.help or have /op
  updater: true