name: '${name}'
main: '${group}.CrazyAuctions'

authors: ${authors}

version: '${version}'
api-version: '${apiVersion}'
description: '${description}'
website: '${website}'

softdepend: [Vault]

commands:
  crazyauctions:
    description: The base command for CrazyAuctions.