name: CrazyAuctions
author: BadBones69
main: com.badbones69.crazyauctions.Main
website: https://www.spigotmc.org/resources/authors/badbones69.9719/
version: ${version}${build.number}
depend: [Vault]
api-version: 1.13
description: A plugin to auction off items globally.
commands:
  ca:
    description: Opens the Crazy Auctions GUI.
    aliases: [crazyauction, crazyauctions, ah, hdv]