name: "CrazyAuctions"
main: "${group}"

authors: [BadBones69, RyderBelserion]

version: ${version}
api-version: "1.18"
description: ${description}

softdepend: [Vault, PlaceholderAPI]

website: https://modrinth.com/plugin/crazyauctions

commands:
  crazyauctions:
    description: The base command for Crazy Auctions