name: '${name}'
main: '${group}.${name}'

authors: ${authors}

version: '${version}'
api-version: '${apiVersion}'
description: '${description}'
website: '${website}'
folia-supported: true

softdepend: [Vault]

commands:
  crazyauctions:
    description: Opens the Crazy Auctions GUI.
    aliases: [crazyauction, ah, ca]
